name: CI

on:
  push:
    branches:
      - 2087-windows-build
      - 'releases/*'
  pull_request:
    branches:
      - '*'

env:
  ORG_GRADLE_PROJECT_enableTestDistribution: true
  ORG_GRADLE_PROJECT_junitBuildCacheUsername: ${{ secrets.BUILD_CACHE_USERNAME }}
  ORG_GRADLE_PROJECT_junitBuildCachePassword: ${{ secrets.BUILD_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/main-build
      with:
        arguments: |
          -PenableJaCoCo
          build
          jacocoRootReport
          prepareDocsForUploadToGhPages
    - name: Upload to Codecov.io
      uses: codecov/codecov-action@v2

  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/main-build
